# Site settings
title: "Montqrewa Marketing Türkiye - tr.montqrewa.xyz"
description: > 
  Geleceğin, teknolojinin ve sanatın mükemmelliği.

author: tr.montqrewa.xyz
email: contact@montqrewa.xyz
twitter_username: 
github_username: 

baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://tr.montqrewa.xyz" # the base hostname & protocol for your site

google_analytics_id: UA-112209397-5
disqus_id:

# Build settings
include: [_pages]
markdown: kramdown
permalink: /:year/:month/:title.html

sass:
    style: compressed

exclude: [vendor]

